/**
 * Built-in capability catalog — maps existing product surfaces.
 * Consórcios explicitly excluded. Alvesz is private workspace only.
 */

import type { CapabilityDefinition } from "@/lib/capabilities/types";

function core(
  partial: Partial<CapabilityDefinition> &
    Pick<CapabilityDefinition, "id" | "version" | "name" | "description" | "category" | "scope">
): CapabilityDefinition {
  const defaults: CapabilityDefinition = {
    id: partial.id,
    version: partial.version,
    name: partial.name,
    description: partial.description,
    category: partial.category,
    scope: partial.scope,
    capabilityType: "CORE",
    status: "STABLE",
    defaultEnabled: true,
    core: true,
    dependencies: [],
    conflicts: [],
    requiredRoles: ["any"],
    requiredPermissions: [],
    requiredMigrations: [],
    configSchema: {},
    routes: [],
    navigationItems: [],
    actions: [],
    agents: [],
    automations: [],
    templates: [],
    limits: {},
    featureFlags: [],
    moduleIds: [],
  };
  return { ...defaults, ...partial, core: true, capabilityType: partial.capabilityType ?? "CORE" };
}

function optional(
  partial: Partial<CapabilityDefinition> &
    Pick<
      CapabilityDefinition,
      "id" | "version" | "name" | "description" | "category" | "capabilityType" | "scope"
    >
): CapabilityDefinition {
  const defaults: CapabilityDefinition = {
    id: partial.id,
    version: partial.version,
    name: partial.name,
    description: partial.description,
    category: partial.category,
    scope: partial.scope,
    capabilityType: partial.capabilityType,
    status: "STABLE",
    defaultEnabled: false,
    core: false,
    dependencies: [{ capabilityId: "core.auth", optional: false }],
    conflicts: [],
    requiredRoles: ["member"],
    requiredPermissions: [],
    requiredMigrations: [],
    configSchema: {},
    routes: [],
    navigationItems: [],
    actions: [],
    agents: [],
    automations: [],
    templates: [],
    limits: {},
    featureFlags: [],
    moduleIds: [],
  };
  return { ...defaults, ...partial, core: false };
}

export const BUILTIN_CAPABILITIES: CapabilityDefinition[] = [
  // —— Core ——
  core({
    id: "core.auth",
    version: "1.0.0",
    name: "Autenticação",
    description: "Login, sessão e identidade de conta",
    category: "security",
    scope: "SYSTEM",
    routes: ["/login", "/auth"],
  }),
  core({
    id: "core.profiles",
    version: "1.0.0",
    name: "Profiles",
    description: "Perfis de usuário",
    category: "identity",
    scope: "SYSTEM",
    routes: ["/dashboard/perfil"],
    dependencies: [{ capabilityId: "core.auth" }],
  }),
  core({
    id: "core.workspaces",
    version: "1.0.0",
    name: "Workspaces",
    description: "Workspaces multi-membro e contexto",
    category: "tenancy",
    scope: "SYSTEM",
    routes: ["/dashboard/workspace"],
    dependencies: [{ capabilityId: "core.auth" }],
  }),
  core({
    id: "core.permissions",
    version: "1.0.0",
    name: "Permissions",
    description: "RBAC e avaliação de ações",
    category: "security",
    scope: "SYSTEM",
    dependencies: [{ capabilityId: "core.workspaces" }],
  }),
  core({
    id: "core.aura-home",
    version: "1.0.0",
    name: "Aura Home",
    description: "Home operacional do Aura Brain",
    category: "shell",
    scope: "SYSTEM",
    routes: ["/dashboard"],
    navigationItems: [{ id: "home", href: "/dashboard", label: "Aura Home", hideable: false }],
    dependencies: [{ capabilityId: "core.auth" }],
  }),
  core({
    id: "core.orchestrator",
    version: "1.0.0",
    name: "Orchestrator",
    description: "Sistema operacional do Aura (Sprint 9.0)",
    category: "cognitive",
    scope: "SYSTEM",
    dependencies: [{ capabilityId: "core.aura-home" }],
  }),
  core({
    id: "core.identity",
    version: "1.0.0",
    name: "Identity Engine",
    description: "Claims e identidade cognitiva",
    category: "cognitive",
    scope: "SYSTEM",
    routes: ["/dashboard/settings/identity"],
  }),
  core({
    id: "core.memory",
    version: "1.0.0",
    name: "Memory Engine",
    description: "Memória persistente e elegível",
    category: "cognitive",
    scope: "SYSTEM",
    routes: ["/dashboard/memoria", "/dashboard/settings/memory"],
  }),
  core({
    id: "core.world-model",
    version: "1.0.0",
    name: "World Model",
    description: "Entidades e relacionamentos",
    category: "cognitive",
    scope: "SYSTEM",
    routes: ["/dashboard/settings/world-model"],
  }),
  core({
    id: "core.cognitive",
    version: "1.0.0",
    name: "Cognitive Engine",
    description: "Padrões, insights e recomendações cognitivas",
    category: "cognitive",
    scope: "SYSTEM",
    routes: ["/dashboard/settings/insights"],
  }),
  core({
    id: "core.discovery",
    version: "1.0.0",
    name: "Discovery",
    description: "Detectores de oportunidades e riscos",
    category: "cognitive",
    scope: "SYSTEM",
    routes: ["/dashboard/discovery"],
  }),
  core({
    id: "core.decision-support",
    version: "1.0.0",
    name: "Decision Support",
    description: "Foundation de decisões",
    category: "cognitive",
    scope: "SYSTEM",
    routes: ["/dashboard/decisions"],
  }),
  core({
    id: "core.planner",
    version: "1.0.0",
    name: "Planner base",
    description: "Plan Center e engines de plano",
    category: "cognitive",
    scope: "SYSTEM",
    routes: ["/dashboard/plans"],
  }),
  core({
    id: "core.audit",
    version: "1.0.0",
    name: "Audit",
    description: "Trilhas de auditoria do produto",
    category: "security",
    scope: "SYSTEM",
    routes: ["/dashboard/logs"],
  }),
  core({
    id: "core.settings",
    version: "1.0.0",
    name: "Configurações",
    description: "Central de configurações",
    category: "shell",
    scope: "SYSTEM",
    routes: ["/dashboard/settings"],
  }),
  core({
    id: "core.search",
    version: "1.0.0",
    name: "Busca",
    description: "Busca global e command palette",
    category: "shell",
    scope: "SYSTEM",
  }),
  core({
    id: "core.notifications",
    version: "1.0.0",
    name: "Notificações",
    description: "Alertas internos",
    category: "shell",
    scope: "SYSTEM",
    routes: ["/dashboard/notificacoes"],
  }),
  core({
    id: "core.security",
    version: "1.0.0",
    name: "Segurança",
    description: "RLS, limites e proteção de superfície",
    category: "security",
    scope: "SYSTEM",
  }),
  core({
    id: "core.conversation",
    version: "1.0.0",
    name: "Command Center",
    description: "Conversational Command Center",
    category: "shell",
    scope: "SYSTEM",
    routes: ["/dashboard/brain"],
    dependencies: [{ capabilityId: "core.orchestrator" }],
  }),

  // —— Optional modules ——
  optional({
    id: "module.financeiro",
    version: "1.0.0",
    name: "Financeiro",
    description: "Controle financeiro pessoal",
    category: "vida",
    capabilityType: "MODULE",
    scope: "USER",
    defaultEnabled: true,
    routes: ["/dashboard/financeiro"],
    moduleIds: ["financeiro"],
    navigationItems: [
      { id: "financeiro", href: "/dashboard/financeiro", label: "Financeiro", section: "vida" },
    ],
    actions: ["create_financial_entry_draft", "create_financial_entry_final"],
  }),
  optional({
    id: "module.saude",
    version: "1.0.0",
    name: "Saúde",
    description: "Treino, hábitos e mente",
    category: "vida",
    capabilityType: "MODULE",
    scope: "USER",
    defaultEnabled: true,
    routes: ["/dashboard/saude"],
    moduleIds: ["saude"],
    navigationItems: [
      { id: "saude", href: "/dashboard/saude", label: "Saúde", section: "vida" },
    ],
    actions: ["complete_habit", "create_workout_plan_draft"],
  }),
  optional({
    id: "module.idiomas",
    version: "1.0.0",
    name: "Idiomas",
    description: "Coach de idiomas",
    category: "vida",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/idiomas"],
    moduleIds: ["idiomas"],
    navigationItems: [
      { id: "idiomas", href: "/dashboard/idiomas", label: "Idiomas", section: "vida" },
    ],
  }),
  optional({
    id: "module.viagens",
    version: "1.0.0",
    name: "Viagens",
    description: "Planejamento de viagens",
    category: "vida",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/viagens"],
    moduleIds: ["viagens"],
    navigationItems: [
      { id: "viagens", href: "/dashboard/viagens", label: "Viagens", section: "vida" },
    ],
  }),
  optional({
    id: "module.knowledge",
    version: "1.0.0",
    name: "Knowledge Hub",
    description: "Documentos e conhecimento",
    category: "aura",
    capabilityType: "MODULE",
    scope: "USER",
    defaultEnabled: true,
    routes: ["/dashboard/knowledge"],
    moduleIds: ["knowledge"],
    navigationItems: [
      { id: "knowledge", href: "/dashboard/knowledge", label: "Knowledge Hub", section: "aura" },
    ],
  }),
  optional({
    id: "module.projects",
    version: "1.0.0",
    name: "Projects",
    description: "Projects OS",
    category: "aura",
    capabilityType: "MODULE",
    scope: "USER",
    defaultEnabled: true,
    routes: ["/dashboard/projects"],
    navigationItems: [
      { id: "projects", href: "/dashboard/projects", label: "Projetos", section: "aura" },
    ],
    actions: ["update_project_status"],
  }),
  optional({
    id: "module.business",
    version: "1.0.0",
    name: "Business",
    description: "Business Hub",
    category: "aura",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/business"],
    navigationItems: [
      { id: "business", href: "/dashboard/business", label: "Business Hub", section: "aura" },
    ],
    actions: ["create_business_idea_draft"],
  }),
  optional({
    id: "module.expert-brain",
    version: "1.0.0",
    name: "Expert Brain",
    description: "Ingestão de cursos e frameworks",
    category: "negocios",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/expert-brain"],
    moduleIds: ["expert-brain"],
    actions: ["retry_expert_brain_document"],
  }),
  optional({
    id: "module.scenarios",
    version: "1.0.0",
    name: "Scenarios",
    description: "Scenario Center",
    category: "cognitive",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/scenarios"],
    dependencies: [
      { capabilityId: "core.auth" },
      { capabilityId: "core.decision-support" },
    ],
  }),
  optional({
    id: "module.prioritization",
    version: "1.0.0",
    name: "Prioritization",
    description: "Priority Center",
    category: "cognitive",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/priorities"],
  }),
  optional({
    id: "module.recommendations",
    version: "1.0.0",
    name: "Recommendations",
    description: "Recommendation Center",
    category: "cognitive",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/recommendations"],
  }),
  optional({
    id: "module.automations",
    version: "1.0.0",
    name: "Automations",
    description: "Automation Engine",
    category: "cognitive",
    capabilityType: "AUTOMATION",
    scope: "USER",
    routes: ["/dashboard/automations"],
    dependencies: [
      { capabilityId: "core.auth" },
      { capabilityId: "core.planner" },
    ],
  }),
  optional({
    id: "module.agents",
    version: "1.0.0",
    name: "Agents",
    description: "Agent Runtime",
    category: "cognitive",
    capabilityType: "AGENT",
    scope: "USER",
    routes: ["/dashboard/agents"],
    agents: [
      "daily_organizer_v1",
      "plan_assistant_v1",
      "project_review_v1",
      "knowledge_organizer_v1",
      "business_preparation_v1",
    ],
    dependencies: [
      { capabilityId: "core.auth" },
      { capabilityId: "module.automations", optional: true },
    ],
  }),
  optional({
    id: "module.learning",
    version: "1.0.0",
    name: "Learning",
    description: "Continuous Learning Engine",
    category: "cognitive",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/learning"],
  }),
  optional({
    id: "module.missions",
    version: "1.0.0",
    name: "Missões",
    description: "Mission Engine",
    category: "vida",
    capabilityType: "MODULE",
    scope: "USER",
    defaultEnabled: true,
    routes: ["/dashboard/missions"],
    moduleIds: ["missions"],
    actions: ["create_mission_reminder", "create_mission_task_draft"],
  }),
  optional({
    id: "module.calendario",
    version: "1.0.0",
    name: "Calendário",
    description: "Agenda inteligente",
    category: "vida",
    capabilityType: "MODULE",
    scope: "USER",
    defaultEnabled: true,
    routes: ["/dashboard/calendario"],
    moduleIds: ["calendario"],
    actions: ["create_calendar_event", "create_calendar_event_draft"],
  }),
  optional({
    id: "module.creator",
    version: "1.0.0",
    name: "Creator",
    description: "Aura Creator e pipeline de conteúdo",
    category: "negocios",
    capabilityType: "MODULE",
    scope: "USER",
    routes: ["/dashboard/creator"],
    moduleIds: ["creator"],
    actions: ["create_content_idea_draft"],
  }),
  optional({
    id: "module.platform-skills",
    version: "1.0.0",
    name: "Skill Center",
    description: "Instalação e gestão de skills",
    category: "platform",
    capabilityType: "VIEW",
    scope: "SYSTEM",
    defaultEnabled: true,
    routes: ["/dashboard/skills", "/dashboard/settings/capabilities"],
    navigationItems: [
      { id: "skills", href: "/dashboard/skills", label: "Skills", section: "aura" },
      {
        id: "capabilities-settings",
        href: "/dashboard/settings/capabilities",
        label: "Capabilities",
        section: "configuracoes",
      },
    ],
  }),

  // —— Private workspace: Alvesz (never generic) ——
  optional({
    id: "workspace.alvesz",
    version: "1.0.0",
    name: "Alvesz Experience",
    description: "CRM, propostas, eventos e estoque — exclusivo do workspace autorizado",
    category: "private",
    capabilityType: "MODULE",
    scope: "PRIVATE_WORKSPACE",
    privateWorkspace: true,
    allowedWorkspaceSlugs: ["alvesz"],
    defaultEnabled: false,
    routes: ["/dashboard/alvesz"],
    moduleIds: ["alvesz"],
    requiredRoles: ["member"],
    requiredPermissions: ["workspace.member"],
    navigationItems: [
      {
        id: "alvesz",
        href: "/dashboard/alvesz",
        label: "Alvesz Experience",
        section: "alvesz",
      },
    ],
  }),
];

/** Explicit exclusion — Consórcios must not reappear as a capability. */
export const EXCLUDED_CAPABILITY_IDS = ["module.consorcios", "consorcios"] as const;

export const CAPABILITY_AUDIT_MATRIX: import("@/lib/capabilities/types").CapabilityMatrixRow[] =
  [
    { capability: "Autenticação", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Profiles", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Workspaces", core: true, optional: false, customizable: true, shareable: true, disableable: false },
    { capability: "Permissions", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Aura Home", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Orchestrator", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Identity", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Memory", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "World Model", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Cognitive", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Discovery", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Decision Support", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Planner base", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Audit", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Configurações", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Busca", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Notificações", core: true, optional: false, customizable: true, shareable: false, disableable: false },
    { capability: "Segurança", core: true, optional: false, customizable: false, shareable: false, disableable: false },
    { capability: "Financeiro", core: false, optional: true, customizable: true, shareable: false, disableable: true },
    { capability: "Saúde", core: false, optional: true, customizable: true, shareable: false, disableable: true },
    { capability: "Idiomas", core: false, optional: true, customizable: true, shareable: false, disableable: true },
    { capability: "Viagens", core: false, optional: true, customizable: true, shareable: false, disableable: true },
    { capability: "Knowledge Hub", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Projects", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Business", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Expert Brain", core: false, optional: true, customizable: true, shareable: false, disableable: true },
    { capability: "Scenarios", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Prioritization", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Recommendations", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Automations", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Agents", core: false, optional: true, customizable: true, shareable: true, disableable: true },
    { capability: "Learning", core: false, optional: true, customizable: true, shareable: false, disableable: true },
    { capability: "Alvesz Experience", core: false, optional: true, customizable: true, shareable: false, disableable: true },
  ];
