/**
 * Built-in Skills V1 — group existing capabilities; no duplicated logic.
 */

import type { SkillDefinition } from "@/lib/capabilities/types";

export const BUILTIN_SKILLS: SkillDefinition[] = [
  {
    id: "skill.daily-planning",
    slug: "daily-planning",
    name: "Daily Planning",
    description: "Organiza o dia com calendário, missões e planner",
    version: "1.0.0",
    category: "productivity",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.calendario", "module.missions", "core.planner"],
    requiredCapabilities: ["core.aura-home", "core.orchestrator"],
    permissions: ["capability.install"],
    riskLevel: "LOW",
    configSchema: { focusHours: { type: "number", default: 4 } },
    defaultConfig: { focusHours: 4 },
    icon: "calendar",
    documentation: "/docs/platform/skills.md#daily-planning",
    uninstallable: true,
  },
  {
    id: "skill.project-review",
    slug: "project-review",
    name: "Project Review",
    description: "Revisão de projetos com agents e prioridades",
    version: "1.0.0",
    category: "projects",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.projects", "module.agents", "module.prioritization"],
    requiredCapabilities: ["core.discovery"],
    permissions: ["capability.install"],
    riskLevel: "LOW",
    configSchema: {},
    defaultConfig: {},
    icon: "folder",
    documentation: "/docs/platform/skills.md#project-review",
    uninstallable: true,
  },
  {
    id: "skill.knowledge-organization",
    slug: "knowledge-organization",
    name: "Knowledge Organization",
    description: "Organiza Knowledge Hub e Memory",
    version: "1.0.0",
    category: "knowledge",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.knowledge", "core.memory"],
    requiredCapabilities: ["core.world-model"],
    permissions: ["capability.install"],
    riskLevel: "LOW",
    configSchema: {},
    defaultConfig: {},
    icon: "book",
    documentation: "/docs/platform/skills.md#knowledge-organization",
    uninstallable: true,
  },
  {
    id: "skill.business-idea-preparation",
    slug: "business-idea-preparation",
    name: "Business Idea Preparation",
    description: "Prepara ideias de negócio com Business Hub e agents",
    version: "1.0.0",
    category: "business",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.business", "module.agents", "module.recommendations"],
    requiredCapabilities: ["core.decision-support"],
    permissions: ["capability.install"],
    riskLevel: "MEDIUM",
    configSchema: {},
    defaultConfig: {},
    icon: "briefcase",
    documentation: "/docs/platform/skills.md#business-idea-preparation",
    uninstallable: true,
  },
  {
    id: "skill.financial-organization",
    slug: "financial-organization",
    name: "Financial Organization",
    description: "Organização financeira pessoal",
    version: "1.0.0",
    category: "finance",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.financeiro"],
    requiredCapabilities: ["core.auth"],
    permissions: ["capability.install"],
    riskLevel: "MEDIUM",
    configSchema: {},
    defaultConfig: {},
    icon: "wallet",
    documentation: "/docs/platform/skills.md#financial-organization",
    uninstallable: true,
  },
  {
    id: "skill.health-routine",
    slug: "health-routine",
    name: "Health Routine",
    description: "Rotina de saúde e hábitos",
    version: "1.0.0",
    category: "health",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.saude"],
    requiredCapabilities: ["core.auth"],
    permissions: ["capability.install"],
    riskLevel: "LOW",
    configSchema: {},
    defaultConfig: {},
    icon: "heart",
    documentation: "/docs/platform/skills.md#health-routine",
    uninstallable: true,
  },
  {
    id: "skill.mission-planning",
    slug: "mission-planning",
    name: "Mission Planning",
    description: "Planejamento de missões com planner",
    version: "1.0.0",
    category: "missions",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.missions", "core.planner"],
    requiredCapabilities: ["core.discovery"],
    permissions: ["capability.install"],
    riskLevel: "LOW",
    configSchema: {},
    defaultConfig: {},
    icon: "target",
    documentation: "/docs/platform/skills.md#mission-planning",
    uninstallable: true,
  },
  {
    id: "skill.content-preparation",
    slug: "content-preparation",
    name: "Content Preparation",
    description: "Preparação de conteúdo com Creator",
    version: "1.0.0",
    category: "creator",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["module.creator"],
    requiredCapabilities: ["core.auth"],
    permissions: ["capability.install"],
    riskLevel: "LOW",
    configSchema: {},
    defaultConfig: {},
    icon: "sparkles",
    documentation: "/docs/platform/skills.md#content-preparation",
    uninstallable: true,
  },
  {
    id: "skill.workspace-collaboration",
    slug: "workspace-collaboration",
    name: "Workspace Collaboration",
    description: "Colaboração em workspace com permissões",
    version: "1.0.0",
    category: "team",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: ["core.workspaces", "core.permissions"],
    requiredCapabilities: ["core.auth"],
    permissions: ["workspace.manage"],
    riskLevel: "MEDIUM",
    configSchema: {},
    defaultConfig: {},
    icon: "users",
    documentation: "/docs/platform/skills.md#workspace-collaboration",
    uninstallable: true,
  },
  {
    id: "skill.alvesz-experience",
    slug: "alvesz-experience",
    name: "Alvesz Experience Skill",
    description:
      "Skill privada do workspace Alvesz — CRM, propostas, eventos e estoque",
    version: "1.0.0",
    category: "private",
    authorType: "INTERNAL",
    authorId: "workspace:alvesz",
    visibility: "WORKSPACE",
    status: "STABLE",
    capabilities: ["workspace.alvesz"],
    requiredCapabilities: ["core.workspaces", "core.permissions"],
    permissions: ["workspace.member"],
    riskLevel: "MEDIUM",
    configSchema: {},
    defaultConfig: {},
    icon: "building",
    documentation: "/docs/platform/private-workspace-skills.md",
    privateWorkspace: true,
    allowedWorkspaceSlugs: ["alvesz"],
    uninstallable: true,
  },
  {
    id: "skill.business-expert",
    slug: "business-expert",
    name: "Business Expert",
    description:
      "Especialização oficial em negócios digitais, locais e empreendedorismo (B1.0 Foundation)",
    version: "1.0.0",
    category: "Business Intelligence",
    authorType: "SYSTEM",
    authorId: "system",
    visibility: "SYSTEM",
    status: "STABLE",
    capabilities: [
      "module.business-expert",
      "core.planner",
      "core.decision-support",
      "module.learning",
    ],
    requiredCapabilities: [
      "core.orchestrator",
      "core.conversation",
      "core.auth",
    ],
    permissions: ["capability.install"],
    riskLevel: "LOW",
    configSchema: {
      focusValidation: { type: "boolean", default: true },
    },
    defaultConfig: { focusValidation: true },
    icon: "briefcase",
    documentation: "/docs/business-expert/foundation.md",
    uninstallable: true,
  },
];
